# 需要发送的topic
kafka-topic:
  zipkin: zipkin-raven

server:
  port: 9411

target:
  url: http://10.0.16.196:9411/api/v2/spans

spring:
  application:
    name: zipkin-collector-pretender
  kafka:
    # 集群地址, 修改为需要发送的 kafka 集群
    bootstrap-servers: 10.0.16.196:18108

    listener:
      #设置是否批量消费，默认 single（单条），batch（批量）
      type: batch

    # 生产者配置
    producer:
      # 重试次数
      retries: 3
      # 应答级别
      # acks=0 把消息发送到kafka就认为发送成功
      # acks=1 把消息发送到kafka leader分区，并且写入磁盘就认为发送成功
      # acks=all 把消息发送到kafka leader分区，并且leader分区的副本follower对消息进行了同步就任务发送成功
      acks: all
      # 批量处理的最大大小 单位 byte
      batch-size: 4096
      # 发送延时,当生产端积累的消息达到batch-size或接收到消息linger.ms后,生产者就会将消息提交给kafka
      buffer-memory: 33554432
      # 客户端ID
      client-id: zipkin-collector-pretender
      # Key 序列化类
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # Value 序列化类
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 消息压缩：none、lz4、gzip、snappy，默认为 none。
      compression-type: gzip
      properties:
        linger:
          # 发送延时,当生产端积累的消息达到batch-size或接收到消息linger.ms后,生产者就会将消息提交给kafka
          ms: 500
        max:
          block:
            # KafkaProducer.send() 和 partitionsFor() 方法的最长阻塞时间 单位 ms
            ms: 6000
        partitioner:
            #指定自定义分区器
            class: com.raven.pretender.partitioner.KeyModPartitioner

    # 消费者配置
    consumer:
      # 默认消费者组
      group-id: zipkin-collector-pretender-consumer
      # 自动提交 offset 默认 true
      enable-auto-commit: true
      # 自动提交的频率 单位 ms
      auto-commit-interval: 1000
      # 批量消费最大数量
      max-poll-records: 1000
      # Key 反序列化类
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # Value 反序列化类
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # 当kafka中没有初始offset或offset超出范围时将自动重置offset
      # earliest:重置为分区中最小的offset
      # latest:重置为分区中最新的offset(消费分区中新产生的数据)
      # none:只要有一个分区不存在已提交的offset,就抛出异常
      auto-offset-reset: latest
      properties:
        session:
          timeout:
            # session超时，超过这个时间consumer没有发送心跳,就会触发reBalance操作
            ms: 120000
        request:
          timeout:
            # 请求超时
            ms: 120000
#        interceptor:
#          classes: com.raven.zipkincollector.interceptor.KafkaConsumerInterceptor


